Repository aws-amplify/amplify-ui, pull requests merged in 2022-08, with the labels that each got.

#2388 docs: Add callout for MapView margin reset
  docs/src/pages/[platform]/connected-components/geo/fragments/margin-reset.react.mdx
  docs/src/pages/[platform]/connected-components/geo/react.mdx
Labels: Documentation, Geo

#2445 test(react): Sort the exported keys of React package for snapshot testing
  packages/react/__tests__/__snapshots__/exports.ts.snap
  packages/react/__tests__/exports.ts
Labels: React

#2460 feat(in-app-messaging): add withInAppMessaging to RN example app
  examples/react-native/App.tsx
  examples/react-native/ios/Podfile.lock
  examples/react-native/metro.config.js
  examples/react-native/package.json
  yarn.lock
Labels: run-tests

#2491 fix(ci): Change e2e environments to auth-with-username-no-attributes
  examples/angular/src/pages/ui/components/authenticator/sign-up-with-username/aws-exports.js
  examples/next/pages/ui/components/authenticator/sign-up-with-username/aws-exports.js
  examples/vue/src/pages/ui/components/authenticator/modal/aws-exports.js
  examples/vue/src/pages/ui/components/authenticator/sign-up-with-username/aws-exports.js
  packages/e2e/features/ui/components/authenticator/sign-up-with-username.feature
Labels: CI

#2511 docs: Add troubleshooting steps for CRA and Geo components
  docs/src/pages/[platform]/getting-started/troubleshooting/troubleshooting.react.mdx
Labels: Documentation
